spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 86400000