spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://prod-db-host:5432/library_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.example.librarymanagement: ERROR